/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.view;

import com.mycompany.duan1.X.MsgBox;
import com.mycompany.duan1.X.Validate;
import com.mycompany.duan1.dao.DiemDAO;
import com.mycompany.duan1.dao.MonHocDao;
import com.mycompany.duan1.dao.SinhVienDao;
import com.mycompany.duan1.model.Diem;
import com.mycompany.duan1.model.MonHoc;
import com.mycompany.duan1.model.SinhVien;
import combobox.Combobox;
import java.awt.Color;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.awt.Scrollbar;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import scrollbar.ScrollBarCustom;
        import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JTable;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ACER
 */
public class QuanLyDiemJPanel extends javax.swing.JPanel {



    /**
     * Creates new form QuanLyDiemJPanel
     */
    public QuanLyDiemJPanel() {
        initComponents();
        init();
    
    }

void init(){
    filltable();
    chonMonHoc();
    txtMaDiem.setEditable(false);
    FillTableInfo();
    fixTable();

}

void fixTable(){
        Scrollbar.getViewport().setBackground(Color.WHITE);
        Scrollbar.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        Scrollbar.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        Scrollbar.setBorder(new EmptyBorder(5, 10, 5, 10));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnTimKiem = new rojeru_san.complementos.RSButtonHover();
        btnThem = new rojeru_san.complementos.RSButtonHover();
        btnXoa = new rojeru_san.complementos.RSButtonHover();
        btnSua = new rojeru_san.complementos.RSButtonHover();
        btnMoi = new rojeru_san.complementos.RSButtonHover();
        cbbMaMonHoc = new combobox.Combobox();
        txtDiemLab1 = new textfield.TextField111();
        txtDiemLab2 = new textfield.TextField1111();
        txtDiemLab3 = new textfield.TextField11111();
        txtDiemLab4 = new textfield.TextField111111();
        txtDiemLab5 = new textfield.TextField1111111();
        txtDiemLab6 = new textfield.TextField11111111();
        txtDiemLab7 = new textfield.TextField11111111_1();
        txtDiemLab8 = new textfield.TextField1111111_1();
        txtDiemASS1 = new textfield.TextField111111_1();
        txtDiemASS2 = new textfield.TextField11111_1();
        txtDoc = new textfield.TextField1111_1();
        txtMaDiem = new textfield.MaDiem();
        txtMaSV = new textfield.MaSinhVien();
        txttimkiem = new textfield.FindMaSinhVien();
        Scrollbar = new javax.swing.JScrollPane();
        tblDiem1 = new rojeru_san.complementos.RSTableMetro();
        btnExel5 = new rojeru_san.complementos.RSButtonHover();
        btnPrint = new rojeru_san.complementos.RSButtonHover();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        txtMaSinhVien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new rojeru_san.complementos.RSTableMetro();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "QUẢN LÍ ĐIỂM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnTimKiem.setBackground(new java.awt.Color(204, 0, 51));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimage/icons/Search.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 0, 51));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimage/icons/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 0, 51));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimage/icons/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 0, 51));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimage/icons/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(204, 0, 51));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimage/icons/Create.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        cbbMaMonHoc.setForeground(new java.awt.Color(0, 204, 51));
        cbbMaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaMonHocActionPerformed(evt);
            }
        });

        txtDiemLab1.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemLab2.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemLab3.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemLab4.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemLab5.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemLab6.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });
        txtDiemLab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemLab6ActionPerformed(evt);
            }
        });

        txtDiemLab7.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemLab8.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemLab8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDiemASS1.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemASS1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });
        txtDiemASS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemASS1ActionPerformed(evt);
            }
        });

        txtDiemASS2.setForeground(new java.awt.Color(0, 204, 51));
        txtDiemASS2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtDoc.setForeground(new java.awt.Color(0, 204, 51));
        txtDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiemLab1FocusLost(evt);
            }
        });

        txtMaDiem.setBackground(new java.awt.Color(204, 204, 204));
        txtMaDiem.setForeground(new java.awt.Color(0, 204, 51));

        txtMaSV.setForeground(new java.awt.Color(0, 204, 51));

        txttimkiem.setForeground(new java.awt.Color(0, 0, 204));

        tblDiem1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Điểm", "Mã Sinh Viên", "Mã Môn Học", "Lab 1", "Lab 2", "Lab 3", "Lab 4", "Lab 5", "Lab 6", "Lab 7", "Lab 8", "Điểm Assignment GD1", "Điểm Assignment GD2", "Điểm Doccument"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiem1.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblDiem1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblDiem1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblDiem1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblDiem1.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tblDiem1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDiem1.setRowHeight(25);
        tblDiem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiem1MouseClicked(evt);
            }
        });
        Scrollbar.setViewportView(tblDiem1);

        btnExel5.setBackground(new java.awt.Color(204, 0, 51));
        btnExel5.setText("Exel");
        btnExel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExel5ActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 0, 51));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbMaMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(txtMaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiemLab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDiemLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiemLab3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiemLab6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemLab5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemLab4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDiemLab8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDiemLab7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiemASS1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiemASS2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addGap(0, 170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Scrollbar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiemLab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemLab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemLab7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemASS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiemLab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemLab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemLab8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(cbbMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiemLab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemLab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiemASS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scrollbar, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );

        tabs.addTab("Quản Lý Điểm", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 204));

        jButton3.setText("Tìm Kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtMaSinhVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtMaSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSinhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSinhVien)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Tên Sinh Viên", "Ngày Sinh", "Email", "Số Điện Thoại", "Địa Chỉ", "Giới Tính", "Mã Chuyên Ngành", "Lớp Học", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblStudent.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblStudent.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblStudent.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblStudent.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblStudent.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblStudent.setRowHeight(40);
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblStudent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Thông Tin Sinh Viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

      Validate vld = new Validate();
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            StringBuilder sb = new StringBuilder();
   
            vld.checkDiem(txtDiemLab1, sb, "Bạn Nhập Điểm Lab 1 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab2, sb, "Bạn Nhập Điểm Lab 2 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab3, sb, "Bạn Nhập Điểm Lab 3 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab4, sb, "Bạn Nhập Điểm Lab 4 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab5, sb, "Bạn Nhập Điểm Lab 5 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab6, sb, "Bạn Nhập Điểm Lab 6 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab7, sb, "Bạn Nhập Điểm Lab 7 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab8, sb, "Bạn Nhập Điểm Lab 8 Không Hợp Lệ");
            vld.checkDiem(txtDiemASS1, sb, "Bạn Nhập Điểm Lab Ass1 Không Hợp Lệ");
            vld.checkDiem(txtDiemASS2, sb, "Bạn Nhập Điểm Lab Ass2 Không Hợp Lệ");
            vld.checkDiem(txtDoc, sb, "Bạn Nhập Điểm Document Không Hợp Lệ");
            
            vld.ValidatorNullJText(txtMaSV, sb, "Mã Sinh Viên Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab1, sb, "Điểm Lab 1 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab2, sb, "Điểm Lab 2 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab3, sb, "Điểm Lab 3 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab4, sb, "Điểm Lab 4 Không Được Để Trống");
                        vld.ValidatorNullJText(txtDiemLab5, sb, "Điểm Lab 5 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab6, sb, "Điểm Lab 6 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab7, sb, "Điểm Lab 7 Không Được Để Trống");
                        vld.ValidatorNullJText(txtDiemLab8, sb, "Điểm Lab 8 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemASS1, sb, "Điểm Ass1 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemASS2, sb, "Điểm Ass2 Không Được Để Trống");
            vld.ValidatorNullJText(txtDoc, sb, "Điểm Doccument Không Được Để Trống");
              if (sb.length() > 0) {
                MsgBox.showErrorDialog(jPanel1, sb.toString(), "Đã Xảy Ra Lỗi");
                return;
          }

         insert();
    
           
       
         
        } catch (Exception e) {
   MsgBox.showErrorDialog(jPanel1, "Có Lỗi Xảy Ra", "Đã Xảy Ra Lỗi");
   e.printStackTrace();
  
    }//GEN-LAST:event_btnThemActionPerformed
    }
    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       StringBuilder sb = new StringBuilder();
   
            vld.checkDiem(txtDiemLab1, sb, "Bạn Nhập Điểm Lab 1 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab2, sb, "Bạn Nhập Điểm Lab 2 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab3, sb, "Bạn Nhập Điểm Lab 3 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab4, sb, "Bạn Nhập Điểm Lab 4 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab5, sb, "Bạn Nhập Điểm Lab 5 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab6, sb, "Bạn Nhập Điểm Lab 6 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab7, sb, "Bạn Nhập Điểm Lab 7 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab8, sb, "Bạn Nhập Điểm Lab 8 Không Hợp Lệ");
            vld.checkDiem(txtDiemASS1, sb, "Bạn Nhập Điểm Lab Ass1 Không Hợp Lệ");
            vld.checkDiem(txtDiemASS2, sb, "Bạn Nhập Điểm Lab Ass2 Không Hợp Lệ");
            vld.checkDiem(txtDoc, sb, "Bạn Nhập Điểm Document Không Hợp Lệ");
            
            vld.ValidatorNullJText(txtMaSV, sb, "Mã Sinh Viên Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab1, sb, "Điểm Lab 1 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab2, sb, "Điểm Lab 2 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab3, sb, "Điểm Lab 3 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab4, sb, "Điểm Lab 4 Không Được Để Trống");
                        vld.ValidatorNullJText(txtDiemLab5, sb, "Điểm Lab 5 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab6, sb, "Điểm Lab 6 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab7, sb, "Điểm Lab 7 Không Được Để Trống");
                        vld.ValidatorNullJText(txtDiemLab8, sb, "Điểm Lab 8 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemASS1, sb, "Điểm Ass1 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemASS2, sb, "Điểm Ass2 Không Được Để Trống");
            vld.ValidatorNullJText(txtDoc, sb, "Điểm Doccument Không Được Để Trống");
              if (sb.length() > 0) {
                MsgBox.showErrorDialog(jPanel1, sb.toString(), "Đã Xảy Ra Lỗi");
                return;
          }
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       StringBuilder sb = new StringBuilder();
   
            vld.checkDiem(txtDiemLab1, sb, "Bạn Nhập Điểm Lab 1 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab2, sb, "Bạn Nhập Điểm Lab 2 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab3, sb, "Bạn Nhập Điểm Lab 3 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab4, sb, "Bạn Nhập Điểm Lab 4 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab5, sb, "Bạn Nhập Điểm Lab 5 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab6, sb, "Bạn Nhập Điểm Lab 6 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab7, sb, "Bạn Nhập Điểm Lab 7 Không Hợp Lệ");
            vld.checkDiem(txtDiemLab8, sb, "Bạn Nhập Điểm Lab 8 Không Hợp Lệ");
            vld.checkDiem(txtDiemASS1, sb, "Bạn Nhập Điểm Lab Ass1 Không Hợp Lệ");
            vld.checkDiem(txtDiemASS2, sb, "Bạn Nhập Điểm Lab Ass2 Không Hợp Lệ");
            vld.checkDiem(txtDoc, sb, "Bạn Nhập Điểm Document Không Hợp Lệ");
            
            vld.ValidatorNullJText(txtMaSV, sb, "Mã Sinh Viên Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab1, sb, "Điểm Lab 1 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab2, sb, "Điểm Lab 2 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab3, sb, "Điểm Lab 3 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab4, sb, "Điểm Lab 4 Không Được Để Trống");
                        vld.ValidatorNullJText(txtDiemLab5, sb, "Điểm Lab 5 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab6, sb, "Điểm Lab 6 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemLab7, sb, "Điểm Lab 7 Không Được Để Trống");
                        vld.ValidatorNullJText(txtDiemLab8, sb, "Điểm Lab 8 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemASS1, sb, "Điểm Ass1 Không Được Để Trống");
            vld.ValidatorNullJText(txtDiemASS2, sb, "Điểm Ass2 Không Được Để Trống");
            vld.ValidatorNullJText(txtDoc, sb, "Điểm Doccument Không Được Để Trống");
              if (sb.length() > 0) {
                MsgBox.showErrorDialog(jPanel1, sb.toString(), "Đã Xảy Ra Lỗi");
                return;
          }
        delete();
// TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
fillSelectDiem();    // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
FillTableInfo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtMaSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSinhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSinhVienActionPerformed

    private void cbbMaMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMaMonHocActionPerformed

    private void txtDiemLab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemLab6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemLab6ActionPerformed

    private void txtDiemASS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemASS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemASS1ActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
 if(evt.getClickCount() == 2){
            this.row = tblStudent.getSelectedRow();
            this.edit2();
     setTrang2();
  
      }
    }//GEN-LAST:event_tblStudentMouseClicked

    private void txtDiemLab1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiemLab1FocusLost

    }//GEN-LAST:event_txtDiemLab1FocusLost

    private void tblDiem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiem1MouseClicked
if(evt.getClickCount() == 2){
row = tblDiem1.getSelectedRow();
edit();        // TODO add your handling code here:
    }//GEN-LAST:event_tblDiem1MouseClicked
    }
    private void btnExel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExel5ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblDiem1.getModel();
        FileOutputStream exelFOU = null;
        BufferedOutputStream exelBOU = null;
        XSSFWorkbook exelJtableExporter = null;
        JFileChooser exelfileChooser = new JFileChooser("D:\\duan1\\DuAn1_Khanh\\Exel");
        exelfileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXEL FILES", "xls", "xlsx", "xlsm");
        exelfileChooser.setFileFilter(fnef);
        int exelChooser = exelfileChooser.showSaveDialog(null);

        if (exelChooser == JFileChooser.APPROVE_OPTION) {

            try {
                exelJtableExporter = new XSSFWorkbook();
                XSSFSheet exelSheet = exelJtableExporter.createSheet("JTable Sheet");
                for (int i = 0; i < model.getRowCount(); i++) {
                    XSSFRow exelRow = exelSheet.createRow(i);

                    for (int j = 0; j < model.getColumnCount(); j++) {
                        XSSFCell exelCell = exelRow.createCell(j);
                        exelCell.setCellValue(model.getValueAt(i, j).toString());
                    }

                }
                exelFOU = new FileOutputStream(exelfileChooser.getSelectedFile() + ".xls");
                exelBOU = new BufferedOutputStream(exelFOU);
                exelJtableExporter.write(exelBOU);
                JOptionPane.showMessageDialog(this, "Export Successfully !");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if(exelBOU != null){
                        exelBOU.close();
                    }
                    if(exelFOU != null){
                        exelFOU.close();
                    }
                    if(exelJtableExporter != null){

                    }
                } catch (IOException ex) {

                    Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnExel5ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header  = new MessageFormat("Item report");

        try {
            tblDiem1.print(JTable.PrintMode.NORMAL, header, null);
            JFileChooser pdfChooser = new JFileChooser("D:\\duan1\\DuAn1_Khanh\\Print");
            pdfChooser.setDialogTitle("Save As");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed
    
    MonHocDao mhdao = new MonHocDao();
    void chonMonHoc(){
        List<MonHoc> list = mhdao.selectAll();
       for (MonHoc mh : list) {
           cbbMaMonHoc.addItem(mh.getMaMonHoc());
       }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scrollbar;
    private rojeru_san.complementos.RSButtonHover btnExel5;
    private rojeru_san.complementos.RSButtonHover btnMoi;
    private rojeru_san.complementos.RSButtonHover btnPrint;
    private rojeru_san.complementos.RSButtonHover btnSua;
    private rojeru_san.complementos.RSButtonHover btnThem;
    private rojeru_san.complementos.RSButtonHover btnTimKiem;
    private rojeru_san.complementos.RSButtonHover btnXoa;
    private combobox.Combobox cbbMaMonHoc;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabs;
    private rojeru_san.complementos.RSTableMetro tblDiem1;
    private rojeru_san.complementos.RSTableMetro tblStudent;
    private textfield.TextField111111_1 txtDiemASS1;
    private textfield.TextField11111_1 txtDiemASS2;
    private textfield.TextField111 txtDiemLab1;
    private textfield.TextField1111 txtDiemLab2;
    private textfield.TextField11111 txtDiemLab3;
    private textfield.TextField111111 txtDiemLab4;
    private textfield.TextField1111111 txtDiemLab5;
    private textfield.TextField11111111 txtDiemLab6;
    private textfield.TextField11111111_1 txtDiemLab7;
    private textfield.TextField1111111_1 txtDiemLab8;
    private textfield.TextField1111_1 txtDoc;
    private textfield.MaDiem txtMaDiem;
    private textfield.MaSinhVien txtMaSV;
    private javax.swing.JTextField txtMaSinhVien;
    private textfield.FindMaSinhVien txttimkiem;
    // End of variables declaration//GEN-END:variables
    int row = -1;
    DiemDAO diemDAO = new DiemDAO();
int i = 1;
   void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblDiem1.getModel();
        model.setRowCount(0);
        List<Diem> list = diemDAO.selectAll();
        for (Diem d : list) {
            String concat = String.format("%.2f",(d.getDiemLab1()+ d.getDiemLab2()+ d.getDiemLab3()+ d.getDiemLab4()+ d.getDiemLab5()+ d.getDiemLab6()+ d.getDiemLab7()+ d.getDiemLab8()+ d.getDiemAsmGD1()+ d.getDiemAsmGD2()) /11);
            Object[] row = {
                d.getMaDiem(),
                d.getMaSV(),
                d.getMaMH(),
                d.getDiemLab1(),
                d.getDiemLab2(),
                d.getDiemLab3(),
                d.getDiemLab4(),
                d.getDiemLab5(),
                d.getDiemLab6(),
                d.getDiemLab7(),
                d.getDiemLab8(),
                d.getDiemAsmGD1(),
                d.getDiemAsmGD2(),
                d.getDiemDoc(),
         concat
            };
            model.addRow(row);
        }
    }
   void fillSelectDiem() {
       try {
                    DefaultTableModel model = (DefaultTableModel)tblDiem1.getModel();
    model.setRowCount(0);
               String keyword = txttimkiem.getText();
            List<Diem> list = diemDAO.selectByMaSV(keyword);
            for (Diem d : list) {
                  String concat = String.format("%.2f",(d.getDiemLab1()+ d.getDiemLab2()+ d.getDiemLab3()+ d.getDiemLab4()+ d.getDiemLab5()+ d.getDiemLab6()+ d.getDiemLab7()+ d.getDiemLab8()+ d.getDiemAsmGD1()+ d.getDiemAsmGD2()) /11);
          Object [] row = {
              
            d.getMaDiem(),
                d.getMaSV(),
                d.getMaMH(),
                d.getDiemLab1(),
                d.getDiemLab2(),
                d.getDiemLab3(),
                d.getDiemLab4(),
                d.getDiemLab5(),
                d.getDiemLab6(),
                d.getDiemLab7(),
                d.getDiemLab8(),
                d.getDiemAsmGD1(),
                d.getDiemAsmGD2(),
                d.getDiemDoc(),
           concat
                  
          };
          model.addRow(row);
           
    }
   
       } catch (Exception e) {
           MsgBox.alert(this, "Lỗi");
           e.printStackTrace();
       }
   
    }
   
    void edit() {
        Integer MaDiem = (Integer) tblDiem1.getValueAt(this.row, 0);
        Diem d = diemDAO.selectByMaDiem(MaDiem);
        tabs.setSelectedIndex(0);
        setForm(d);
    }
     void edit2() {
         String maSV = (String) tblStudent.getValueAt(this.row, 0);
         SinhVien sv = svdao.selectById(maSV);
         this.setForm(sv);
         tabs.setSelectedIndex(0);
    }

  void insert() {
        Diem model = getModel();
        for (int i = 0; i < tblDiem1.getRowCount(); i++) {
            if ((txtMaSV.getText() + cbbMaMonHoc.getSelectedItem().toString()).equals(tblDiem1.getValueAt(i, 1).toString()+tblDiem1.getValueAt(i, 2).toString())){
                MsgBox.alert(this, "Sinh Viên, môn này đã có điểm");
                return ;
            }
        }
        try {
            diemDAO.insert(model);
            this.clear();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
            filltable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
            e.printStackTrace();
        }
    }
       void update() {
           try {
             
                Diem model = getModel();
         diemDAO.update(model);
              MsgBox.alert(this, "Cập nhật thành công");
                   this.filltable();
            
           } catch (Exception e) {
                MsgBox.alert(this, "Lỗi");
                e.printStackTrace();
           }
       
        
    }

 void setForm(Diem d) {
        txtMaDiem.setText(String.valueOf(d.getMaDiem()));
        txtMaSV.setText(d.getMaSV());
        cbbMaMonHoc.setSelectedItem(d.getMaMH());
        txtDiemASS1.setText(String.valueOf(d.getDiemAsmGD1()));
        txtDiemASS2.setText(String.valueOf(d.getDiemAsmGD2()));
        txtDiemLab1.setText(String.valueOf(d.getDiemLab1()));
        txtDiemLab2.setText(String.valueOf(d.getDiemLab2()));
        txtDiemLab3.setText(String.valueOf(d.getDiemLab3()));
        txtDiemLab4.setText(String.valueOf(d.getDiemLab4()));
        txtDiemLab5.setText(String.valueOf(d.getDiemLab5()));
        txtDiemLab6.setText(String.valueOf(d.getDiemLab6()));
        txtDiemLab7.setText(String.valueOf(d.getDiemLab7()));
        txtDiemLab8.setText(String.valueOf(d.getDiemLab8()));
        txtDoc.setText(String.valueOf(d.getDiemDoc()));
        
    }

    Diem getModel() {
        Diem model = new Diem();
        model.setMaSV(txtMaSV.getText());
        model.setMaMH((String) cbbMaMonHoc.getSelectedItem());
        model.setDiemLab1(Float.valueOf(txtDiemLab1.getText()));
        model.setDiemLab2(Float.valueOf(txtDiemLab2.getText()));
        model.setDiemLab3(Float.valueOf(txtDiemLab3.getText()));
        model.setDiemLab4(Float.valueOf(txtDiemLab4.getText()));
        model.setDiemLab5(Float.valueOf(txtDiemLab5.getText()));
        model.setDiemLab6(Float.valueOf(txtDiemLab6.getText()));
        model.setDiemLab7(Float.valueOf(txtDiemLab7.getText()));
        model.setDiemLab8(Float.valueOf(txtDiemLab8.getText()));
        model.setDiemAsmGD1(Float.valueOf(txtDiemASS1.getText()));
        model.setDiemAsmGD2(Float.valueOf(txtDiemASS2.getText()));
        model.setDiemDoc(Float.valueOf(txtDoc.getText()));
//        model.setMaDiem(Integer.valueOf(txtMaDiem.getText()));
        return model;
    }
 

    public void setTrang() {
        txtMaDiem.setBackground(white);
        txtMaSV.setBackground(white);
        cbbMaMonHoc.setBackground(white);
        txtDiemLab1.setBackground(white);
        txtDiemASS1.setBackground(white);
        txtMaDiem.setText(" ");
        txtMaSV.setText(" ");
        cbbMaMonHoc.setToolTipText("");
        txtDiemLab1.setText(" ");
        txtDiemLab2.setText(" ");
        txtDiemLab3.setText(" ");
        txtDiemLab4.setText(" ");
        txtDiemLab5.setText(" ");
        txtDiemLab6.setText(" ");
        txtDiemLab7.setText(" ");
        txtDiemLab8.setText(" ");
        txtDiemASS1.setText(" ");
        txtDiemASS2.setText(" ");
        txtDoc.setText(" ");
  
        txttimkiem.setText("");
    }
    public void setTrang2() {
    
        txtMaDiem.setText(" ");
        
        cbbMaMonHoc.setToolTipText("");
        txtDiemLab1.setText(" ");
        txtDiemLab2.setText(" ");
        txtDiemLab3.setText(" ");
        txtDiemLab4.setText(" ");
        txtDiemLab5.setText(" ");
        txtDiemLab6.setText(" ");
        txtDiemLab7.setText(" ");
        txtDiemLab8.setText(" ");
        txtDiemASS1.setText(" ");
        txtDiemASS2.setText(" ");
        txtDoc.setText(" ");

        txttimkiem.setText("");
    }

    void clear() {
        setTrang();

    }

    void delete() {
   String madiem = txtMaDiem.getText();
        try {
            diemDAO.delete(madiem);
            this.clear();
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            filltable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa Thất Bại!");
        }

    }
    SinhVienDao svdao = new SinhVienDao();
    void FillTableInfo(){
            DefaultTableModel model = (DefaultTableModel)tblStudent.getModel();
    model.setRowCount(0);
               String keyword = txtMaSinhVien.getText();
            List<SinhVien> list = svdao.selectByKeyword(keyword);
            for (SinhVien sv : list) {
          Object [] row = {
           
          sv.getMaSinhVien(),
              sv.getTenSinhVien(),
              sv.getNgaySinh(),
              sv.getEmail(),
              sv.getSDT(),
              sv.getDiaChi(),
              sv.isGioiTinh(),
              sv.getMaChuyenNganh(),
              sv.getMaLopHoc(),
              sv.getHinh()
                  
          };
          model.addRow(row);
    }
    }

    private void setForm(SinhVien sv) {
       txtMaSV.setText(sv.getMaSinhVien());
    }

    
}
