/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.jaspersoft.ireport.designer.JrxmlLoader;
import com.mycompany.duan1.X.MsgBox;
import com.mycompany.duan1.X.XImage;
import com.mycompany.duan1.X.XJdbc;
import com.mycompany.duan1.dao.ChuyenNganhDao;
import com.mycompany.duan1.dao.LopHocDAO;
import com.mycompany.duan1.dao.SinhVienDao;
import com.mycompany.duan1.model.ChuyenNganh;
import com.mycompany.duan1.model.LopHoc;
import com.mycompany.duan1.model.SinhVien;
import com.raven.datechooser.SelectedDate;
import com.sun.jdi.connect.spi.Connection;
import com.toedter.calendar.JDateChooser;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.time.Instant;
import javax.swing.JComboBox;
import java.sql.PreparedStatement;
import static java.sql.DriverManager.getConnection;
import java.text.MessageFormat;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import scrollbar.ScrollBarCustom;

/**
 *
 * @author ADMIN
 */
public class SinhVienJPanel extends javax.swing.JPanel {

    private List<SinhVien> sinhvien;

    /**
     * Creates new form HocVienJPanel
     */
    public SinhVienJPanel() {
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnView = new javax.swing.JPanel();
        Scrollbar = new javax.swing.JScrollPane();
        tblStudent = new rojeru_san.complementos.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaSinhVien = new textfield.MaSinhVien();
        txtHoTen = new textfield.TenSinhVien();
        cbbmachuyennganh = new combobox.CBBMaChuyenNganh();
        cbbmalophoc = new combobox.CBBMaLopHoc();
        txtDiaChi = new textfield.DiaChi();
        txtSoDienThoai = new textfield.SDT();
        txtEmail = new textfield.Email();
        txtSeach = new textfield.TìmKiếm();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        btnsubmit = new rojeru_san.complementos.RSButtonHover();
        btnUpdate = new rojeru_san.complementos.RSButtonHover();
        btnNew = new rojeru_san.complementos.RSButtonHover();
        btnPrint = new rojeru_san.complementos.RSButtonHover();
        btnXoa1 = new rojeru_san.complementos.RSButtonHover();
        btnExel1 = new rojeru_san.complementos.RSButtonHover();

        setBackground(new java.awt.Color(255, 255, 255));

        jpnView.setBackground(new java.awt.Color(255, 255, 255));
        jpnView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Scrollbar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblStudent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Tên Sinh Viên", "Ngày Sinh", "SĐT", "Mã CN", "Mã Lớp Học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblStudent.setColorBordeFilas(new java.awt.Color(153, 153, 153));
        tblStudent.setColorBordeHead(new java.awt.Color(153, 153, 153));
        tblStudent.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblStudent.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblStudent.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblStudent.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        tblStudent.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblStudent.setRowHeight(45);
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        Scrollbar.setViewportView(tblStudent);

        jpnView.add(Scrollbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, 1080, 270));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông Tin Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Ngày Sinh");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Giới Tính");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        rdonam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdonam);
        rdonam.setSelected(true);
        rdonam.setText("Nam");
        jPanel1.add(rdonam, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, -1, -1));

        rdonu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");
        jPanel1.add(rdonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 50, -1));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHinh.setBackground(new java.awt.Color(204, 204, 204));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });
        jPanel3.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 101, 140));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ảnh");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 120, 170));
        jPanel1.add(txtMaSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, -1));
        jPanel1.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, -1));

        cbbmachuyennganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmachuyennganhActionPerformed(evt);
            }
        });
        jPanel1.add(cbbmachuyennganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, -1));
        jPanel1.add(cbbmalophoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, -1));
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 270, -1));
        jPanel1.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 270, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 270, -1));

        txtSeach.setText("Nhập Vào Mã SV,Mã LH, Mã CN,Tên SV");
        txtSeach.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSeachFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeachFocusLost(evt);
            }
        });
        txtSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeachActionPerformed(evt);
            }
        });
        jPanel1.add(txtSeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 240, -1));

        rSButtonHover1.setBackground(new java.awt.Color(204, 0, 51));
        rSButtonHover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myimage/icons/Zoom.png"))); // NOI18N
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 40, -1));

        jdcNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        jdcNgaySinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jdcNgaySinh.setDateFormatString("dd/MM/yyyy");
        jdcNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jdcNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, -1));

        jpnView.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1080, 240));

        btnsubmit.setBackground(new java.awt.Color(204, 0, 51));
        btnsubmit.setText("Lưu");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jpnView.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, -1));

        btnUpdate.setBackground(new java.awt.Color(204, 0, 51));
        btnUpdate.setText("Cập Nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jpnView.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, -1));

        btnNew.setBackground(new java.awt.Color(204, 0, 51));
        btnNew.setText("Làm Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jpnView.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 120, -1));

        btnPrint.setBackground(new java.awt.Color(204, 0, 51));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jpnView.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 110, -1));

        btnXoa1.setBackground(new java.awt.Color(204, 0, 51));
        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });
        jpnView.add(btnXoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 110, -1));

        btnExel1.setBackground(new java.awt.Color(204, 0, 51));
        btnExel1.setText("Exel");
        btnExel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExel1ActionPerformed(evt);
            }
        });
        jpnView.add(btnExel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        if (evt.getClickCount() == 2) {
            row = tblStudent.getSelectedRow();
            edit();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStudentMouseClicked

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        chonAnh();        // TODO add your handling code here:
    }//GEN-LAST:event_lblHinhMouseClicked

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        fillTableSelectByMa();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void txtSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeachActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSeachFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeachFocusGained
        if (txtSeach.getText().equals("Nhập Vào Mã SV,Mã LH, Mã CN,Tên SV")) {
            txtSeach.setText("");
            txtSeach.requestFocus();
            removePlacehoderStyle(txtSeach);
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtSeachFocusGained

    private void txtSeachFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeachFocusLost
        if (txtSeach.getText().length() == 0) {
            addPlacehoderStyle(txtSeach);
            txtSeach.setText("Nhập Vào Mã SV,Mã LH, Mã CN,Tên SV");
    }//GEN-LAST:event_txtSeachFocusLost
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearForm();// TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header  = new MessageFormat("Item report");   
        try {
            tblStudent.print(JTable.PrintMode.NORMAL, header, null);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void cbbmachuyennganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmachuyennganhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbmachuyennganhActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        insert();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
clearForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnExel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExel1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
        FileOutputStream exelFOU = null;
       BufferedOutputStream exelBOU = null;
       XSSFWorkbook exelJtableExporter = null;    
       JFileChooser exelfileChooser = new JFileChooser("D:\\duan1\\DuAn1-Khanh\\Exel");
       exelfileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXEL FILES", "xls", "xlsx", "xlsm");
        exelfileChooser.setFileFilter(fnef);
        int exelChooser = exelfileChooser.showSaveDialog(null);
        
        if (exelChooser == JFileChooser.APPROVE_OPTION) {
           
             try {
                exelJtableExporter = new XSSFWorkbook();
                XSSFSheet exelSheet = exelJtableExporter.createSheet("JTable Sheet");
                for (int i = 0; i < model.getRowCount(); i++) {
                   XSSFRow exelRow = exelSheet.createRow(i);
                   
                   for (int j = 0; j < model.getColumnCount(); j++) {
                        XSSFCell exelCell = exelRow.createCell(j);
                        exelCell.setCellValue(model.getValueAt(i, j).toString());
                    }
                     
                 }   
                exelFOU = new FileOutputStream(exelfileChooser.getSelectedFile() + ".xls");
                exelBOU = new BufferedOutputStream(exelFOU); 
                exelJtableExporter.write(exelBOU);
                JOptionPane.showMessageDialog(this, "Export Successfully !");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if(exelBOU != null){
                        exelBOU.close();
                    }
                    if(exelFOU != null){
                        exelFOU.close();
                    }
                    if(exelJtableExporter != null){
                         
                    }
                } catch (IOException ex) {
                    
                    Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }  
    }//GEN-LAST:event_btnExel1ActionPerformed

    void fixTable() {
        Scrollbar.getViewport().setBackground(Color.WHITE);
        Scrollbar.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        Scrollbar.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        Scrollbar.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    int row = -1;
    SinhVienDao svdao = new SinhVienDao();

    void init() {
        lblHinh.setIcon(XImage.read("noImage.png"));
        filltable();
        chonChuyenNganh();
        chonLopHoc();
        addPlacehoderStyle(txtSeach);
        fixTable();
//    addPlacehoderStyle(txtSoDienThoai);
//    addPlacehoderStyle(txtDiaChi);
//    addPlacehoderStyle(txtEmail);
//    addPlacehoderStyle(txtHoTen);
//    addPlacehoderStyle(txtMaSinhVien);

//  removePlacehoderStyle(txtMaSinhVien);
//  removePlacehoderStyle(txtHoTen);
//  removePlacehoderStyle(txtEmail);
//  removePlacehoderStyle(txtDiaChi);
//  removePlacehoderStyle(txtSoDienThoai);
//  removePlacehoderStyle(txtSeach);
//  removecbbStyle(cbbmachuyennganh);
//  removecbbStyle(cbbmalophoc);
    }

    void edit() {
        String maSV = (String) tblStudent.getValueAt(this.row, 0);
        SinhVien sv = svdao.selectById(maSV);
        setForm(sv);

    }

    void setForm(SinhVien sv) {
        txtMaSinhVien.setText(sv.getMaSinhVien());
        txtHoTen.setText(sv.getTenSinhVien());
        jdcNgaySinh.setDate(sv.getNgaySinh());
        txtEmail.setText(sv.getEmail());
        txtSoDienThoai.setText(sv.getSDT());
        txtDiaChi.setText(sv.getDiaChi());
        cbbmachuyennganh.setSelectedItem(String.valueOf(sv.getMaChuyenNganh()));
        cbbmalophoc.setSelectedItem(String.valueOf(sv.getMaLopHoc()));
        rdonam.setSelected(sv.isGioiTinh() ? true : false);
        rdonu.setSelected(sv.isGioiTinh() ? false : true);

        if (sv.getHinh() != null) {
            lblHinh.setToolTipText(sv.getHinh());
            lblHinh.setIcon(XImage.read(sv.getHinh()));
        } else {
            lblHinh.setIcon(XImage.read("noImage.png"));
        }
    }

    SinhVien getForm() {
        SinhVien sv = new SinhVien();
        sv.setMaSinhVien(txtMaSinhVien.getText());
        sv.setTenSinhVien(txtHoTen.getText());
        sv.setNgaySinh(jdcNgaySinh.getDate());
        sv.setEmail(txtEmail.getText());
        sv.setSDT(txtSoDienThoai.getText());
        sv.setMaChuyenNganh(String.valueOf(cbbmachuyennganh.getSelectedItem()));
        sv.setMaLopHoc(String.valueOf(cbbmalophoc.getSelectedItem()));
        sv.setDiaChi(txtDiaChi.getText());
        sv.setGioiTinh(rdonam.isSelected() ? true : false);

        sv.setHinh(lblHinh.getToolTipText());
        return sv;
    }
    JFileChooser fileChooser = new JFileChooser();

    void chonAnh() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file); // lưu hình vào thư mục logos
            ImageIcon icon = XImage.read(file.getName()); // đọc hình từ logos
            lblHinh.setIcon(icon);
            lblHinh.setToolTipText(file.getName()); // giữ tên hình trong tooltip
        }
    }

    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
        model.setRowCount(0);
        List<SinhVien> list = svdao.selectAll();
        for (SinhVien sv : list) {
            Object[] row = {
                sv.getMaSinhVien(),
                sv.getTenSinhVien(),
                sv.getNgaySinh(),
             
                sv.getSDT(),
         
         
                sv.getMaChuyenNganh(),
                sv.getMaLopHoc()
           

            };
            model.addRow(row);
        }
    }

    void insert() {
        SinhVien model = getForm();
        try {
            svdao.insert(model);

            this.clearForm();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
            filltable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm mới thất bại!");
            e.printStackTrace();
        }
    }

    void update() {
        SinhVien model = getForm();
        try {
            svdao.update(model);
            clearForm();
            JOptionPane.showMessageDialog(this, "Cập Nhật thành công!");
            filltable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập Nhật  thất bại!");
            e.printStackTrace();
        }
    }

    void delete() {

        String masv = txtMaSinhVien.getText();
        try {
            svdao.delete(masv);
            this.clearForm();
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            filltable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa Thất Bại!");
        }

    }

    void clearForm() {
        txtMaSinhVien.setText("");
        txtHoTen.setText("");
        jdcNgaySinh.setDate(null);

        txtEmail.setText("");
        txtSoDienThoai.setText("");
        txtDiaChi.setText("");

        rdonu.isSelected();
        lblHinh.setIcon(XImage.read("noImage.png"));
    }
    ChuyenNganhDao cndao = new ChuyenNganhDao();
    LopHocDAO lhdao = new LopHocDAO();

    void chonChuyenNganh() {
        List<ChuyenNganh> list = cndao.selectAll();
        for (ChuyenNganh cn : list) {
            cbbmachuyennganh.addItem(cn.getMaChuyenNganh());
        }
    }

    void chonLopHoc() {
        List<LopHoc> list = lhdao.selectAll();
        for (LopHoc lh : list) {
            cbbmalophoc.addItem(lh.getMaLopHoc());
        }
    }

    void fillcomboboxLopHoc() {
        String MaCN = (String) cbbmachuyennganh.getSelectedItem();
        List<LopHoc> list = lhdao.selectByChuyenNganh(MaCN);
        for (LopHoc lh : list) {
            cbbmalophoc.addItem(lh.getMaLopHoc());
        }
    }

    void fillTableSelectByMa() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblStudent.getModel();
            model.setRowCount(0);
            String keyword = txtSeach.getText();
            List<SinhVien> list = svdao.selectByMaCNLopHocTen(keyword);
            for (SinhVien nh : list) {
                model.addRow(new Object[]{
                    nh.getMaSinhVien(),
                    nh.getTenSinhVien(),
                    nh.getNgaySinh(),
                  
                    nh.getSDT(),
               
               
                    nh.getMaChuyenNganh(),
                    nh.getMaLopHoc(),
                   });

            }

        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn");
        }

    }

    public void addPlacehoderStyle(JTextField jTextField) {
        Font font = jTextField.getFont();
        font = font.deriveFont(Font.ITALIC);
        jTextField.setFont(font);
        jTextField.setForeground(Color.gray);
    }

    public void removePlacehoderStyle(JTextField jTextField) {
        Font font = jTextField.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        jTextField.setFont(font);
        jTextField.setForeground(Color.black);
    }

    public void removecbbStyle(JComboBox jcbb) {
        Font font = jcbb.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        jcbb.setFont(font);
        jcbb.setForeground(Color.black);
    }

    public void XuatThongtin() {
        try {

            Hashtable map = new Hashtable();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scrollbar;
    private rojeru_san.complementos.RSButtonHover btnExel1;
    private rojeru_san.complementos.RSButtonHover btnNew;
    private rojeru_san.complementos.RSButtonHover btnPrint;
    private rojeru_san.complementos.RSButtonHover btnUpdate;
    private rojeru_san.complementos.RSButtonHover btnXoa1;
    private rojeru_san.complementos.RSButtonHover btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private combobox.CBBMaChuyenNganh cbbmachuyennganh;
    private combobox.CBBMaLopHoc cbbmalophoc;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblHinh;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private rojeru_san.complementos.RSTableMetro tblStudent;
    private textfield.DiaChi txtDiaChi;
    private textfield.Email txtEmail;
    private textfield.TenSinhVien txtHoTen;
    private textfield.MaSinhVien txtMaSinhVien;
    private textfield.TìmKiếm txtSeach;
    private textfield.SDT txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
