/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.duan1.X.Auth;
import com.mycompany.duan1.X.DBConnection;
import com.mycompany.duan1.X.DatabaseConnection;
import com.mycompany.duan1.X.MsgBox;
import com.mycompany.duan1.X.XDate;
import com.mycompany.duan1.X.XJdbc;
import com.mycompany.duan1.controller.MyCombobox;
import com.mycompany.duan1.dao.ChuyenNganhDao;
import com.mycompany.duan1.dao.DAOHoaDon;
import com.mycompany.duan1.dao.HoaDonDao;
import com.mycompany.duan1.dao.HocKyDao;
import com.mycompany.duan1.dao.LopHocDAO;
import com.mycompany.duan1.dao.MonHocDao;
import com.mycompany.duan1.dao.NhanVienDao;
import com.mycompany.duan1.dao.SinhVienDao;
import com.mycompany.duan1.model.ChuyenDoi;
import com.mycompany.duan1.model.ChuyenNganh;
import com.mycompany.duan1.model.HoaDon;
import com.mycompany.duan1.model.HocKy;
import com.mycompany.duan1.model.LopHoc;
import com.mycompany.duan1.model.MonHoc;
import com.mycompany.duan1.model.NhanVien;
import com.mycompany.duan1.model.SinhVien;
import com.sun.jdi.connect.spi.Connection;
import combobox.Combobox;
import java.awt.Color;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import org.apache.log4j.Logger;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
import scrollbar.ScrollBarCustom;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import scrollbar.ScrollBarCustom;
import java.util.logging.Level;
import javax.swing.JTable;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.text.MessageFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ThanhToanDichVu extends javax.swing.JPanel {

    /**
     * Creates new form ThanhToanDichVu
     */
    public ThanhToanDichVu() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbKH = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        rdott = new javax.swing.JRadioButton();
        rdochuatt = new javax.swing.JRadioButton();
        txt_MaNV = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbb_ChuyenNganh = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbb_Lophoc = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbb_Hocky = new javax.swing.JComboBox<>();
        btn_Them = new rojeru_san.complementos.RSButtonHover();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        txtTongTien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Scrollbar = new javax.swing.JScrollPane();
        tblMonHoc = new rojeru_san.complementos.RSTableMetro();
        btnThanhToan = new rojeru_san.complementos.RSButtonHover();
        btn_Xoa = new rojeru_san.complementos.RSButtonHover();
        btnPrint = new rojeru_san.complementos.RSButtonHover();
        btnExel5 = new rojeru_san.complementos.RSButtonHover();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 625));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 625));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 625));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Ngày tạo");

        txtNgayTao.setBackground(new java.awt.Color(245, 245, 245));
        txtNgayTao.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Nhân viên");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Địa chỉ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Sinh Viên");

        cbbKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKHActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("Tình Trạng");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Điện thoại");

        txtDienThoai.setBackground(new java.awt.Color(245, 245, 245));
        txtDienThoai.setEnabled(false);

        rdott.setBackground(new java.awt.Color(245, 245, 245));
        buttonGroup1.add(rdott);
        rdott.setText("Đã T/T");
        rdott.setEnabled(false);

        rdochuatt.setBackground(new java.awt.Color(245, 245, 245));
        buttonGroup1.add(rdochuatt);
        rdochuatt.setSelected(true);
        rdochuatt.setText("Chưa T/T");
        rdochuatt.setEnabled(false);

        txt_MaNV.setBackground(new java.awt.Color(245, 245, 245));
        txt_MaNV.setEnabled(false);

        txtDiaChi.setBackground(new java.awt.Color(245, 245, 245));
        txtDiaChi.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Chuyên ngành");

        cbb_ChuyenNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_ChuyenNganhActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Lớp học");

        cbb_Lophoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_LophocActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Học kỳ");

        cbb_Hocky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_HockyActionPerformed(evt);
            }
        });

        btn_Them.setBackground(new java.awt.Color(204, 0, 51));
        btn_Them.setText("THÊM");
        btn_Them.setColorHover(new java.awt.Color(255, 51, 51));
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(cbbKH, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(rdott)
                        .addGap(11, 11, 11)
                        .addComponent(rdochuatt)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_Hocky, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_ChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbb_Lophoc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbb_ChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(cbb_Lophoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdott)
                        .addComponent(jLabel15))
                    .addComponent(rdochuatt)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel11)
                        .addComponent(cbb_Hocky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sinh Viên", "Mã Chuyên Ngành", "Học Kỳ", "Thành tiền", "Số môn học", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_HoaDon);
        if (tbl_HoaDon.getColumnModel().getColumnCount() > 0) {
            tbl_HoaDon.getColumnModel().getColumn(0).setMinWidth(3);
            tbl_HoaDon.getColumnModel().getColumn(0).setPreferredWidth(3);
            tbl_HoaDon.getColumnModel().getColumn(1).setResizable(false);
            tbl_HoaDon.getColumnModel().getColumn(4).setResizable(false);
            tbl_HoaDon.getColumnModel().getColumn(6).setMinWidth(10);
            tbl_HoaDon.getColumnModel().getColumn(6).setPreferredWidth(10);
        }

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtTongTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTongTienFocusLost(evt);
            }
        });
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Tổng cộng");

        tblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã MH", "Tên MH", "Học Phí", "Học Kỳ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonHoc.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblMonHoc.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblMonHoc.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblMonHoc.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblMonHoc.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblMonHoc.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblMonHoc.setRowHeight(25);
        Scrollbar.setViewportView(tblMonHoc);

        btnThanhToan.setBackground(new java.awt.Color(204, 0, 51));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.setColorHover(new java.awt.Color(255, 51, 51));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(204, 0, 51));
        btn_Xoa.setText("XOÁ");
        btn_Xoa.setColorHover(new java.awt.Color(255, 51, 51));
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 0, 51));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnExel5.setBackground(new java.awt.Color(204, 0, 51));
        btnExel5.setText("Exel");
        btnExel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExel5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(btnExel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Scrollbar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Scrollbar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    int row = -1;
    HoaDonDao hddao = new HoaDonDao();
    ChuyenNganhDao cnDao = new ChuyenNganhDao();
    SinhVienDao svDao = new SinhVienDao();
    LopHocDAO lhDao = new LopHocDAO();
    MonHocDao mhDao = new MonHocDao();
    NhanVienDao nvdao = new NhanVienDao();
    HocKyDao hkdao = new HocKyDao();

    void fixTable() {
        Scrollbar.getViewport().setBackground(Color.WHITE);
        Scrollbar.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        Scrollbar.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        Scrollbar.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    private void cbbKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKHActionPerformed
        if (cbbKH.getSelectedItem() != null) {
            FillTableHoaDon();
            String sdt = svDao.selectById(cbbKH.getSelectedItem().toString()).getSDT();
            String diachi = svDao.selectById(cbbKH.getSelectedItem().toString()).getDiaChi();
            txtDienThoai.setText(sdt);
            txtDiaChi.setText(diachi);
            Filltable(null);
            fillComboBoxHocKi();
        }
    }//GEN-LAST:event_cbbKHActionPerformed
    
    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtTongTienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTongTienFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienFocusLost

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        HoaDon hd = new HoaDon();
        hd.setTinhTrang(true);
        hd.setMaHoaDon(Integer.parseInt(tbl_HoaDon.getValueAt(row, 0).toString()));
        hd.setTongTien(Double.valueOf(txtTongTien.getText()));
        //Thêm hóa đơn vào database
        hddao.update(hd);
        MsgBox.alert(this, "Đã Thanh Toán Cho Sinh Viên");
        FillTableHoaDon();
        Filltable(null);
        txtTongTien.setText("");
       
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cbb_ChuyenNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_ChuyenNganhActionPerformed
        if (cbb_ChuyenNganh.getSelectedItem() != null) {
            fillcomboboxLopHoc();
            Filltable(null);
            fillComboBoxHocKi();
        }
    }//GEN-LAST:event_cbb_ChuyenNganhActionPerformed

    private void cbb_LophocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_LophocActionPerformed
        if (cbb_Lophoc.getSelectedItem() != null) {
            fillComboBoxSinhVien();
            Filltable(null);
            fillComboBoxHocKi();
        }
    }//GEN-LAST:event_cbb_LophocActionPerformed

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        if (tbl_HoaDon != null) {
            row = tbl_HoaDon.getSelectedRow();
            String MaHK = tbl_HoaDon.getValueAt(row, 3).toString();
            Filltable(MaHK);
            txtTongTien.setText(tbl_HoaDon.getValueAt(row, 4).toString());
        } else {
            Filltable(null);
        }
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
       
        HoaDon hd = new HoaDon();
        hd.setNgayTaoHoaDon(XDate.toDate(txtNgayTao.getText(), "dd/MM/yyyy"));
        hd.setMaNhanVien(txt_MaNV.getText());
        hd.setMaSinhVien(cbbKH.getSelectedItem().toString());
        hd.setMaChuyenNganh(cbb_ChuyenNganh.getSelectedItem().toString());
        hd.setTinhTrang(false);
        hd.setHocKy(cbb_Hocky.getSelectedItem().toString()); 

  
 //Thêm hóa đơn vào database
        hddao.insert(hd);

        MsgBox.alert(this, "Đã Thêm Học Phí Thành Công");
            FillTableHoaDon();
            Filltable(null);
        fillComboBoxHocKi();
        txtTongTien.setText("");
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        String id = tbl_HoaDon.getValueAt(row, 0).toString();
        //Thêm hóa đơn vào database
        hddao.delete(id);
        MsgBox.alert(this, "Xoá Thành Công");
        FillTableHoaDon();
        Filltable(null);
        fillComboBoxHocKi();
        txtTongTien.setText("");
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void cbb_HockyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_HockyActionPerformed
       
    }//GEN-LAST:event_cbb_HockyActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header  = new MessageFormat("THANH TOÁN HỌC PHÍ SINH VIÊN");

        try {
            tbl_HoaDon.print(JTable.PrintMode.NORMAL, header, null);
            JFileChooser pdfChooser = new JFileChooser("D:\\duan1\\DuAn1_Khanh\\Print");
            pdfChooser.setDialogTitle("Save As");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnExel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExel5ActionPerformed

        DefaultTableModel model = (DefaultTableModel) tbl_HoaDon.getModel();
        FileOutputStream exelFOU = null;
        BufferedOutputStream exelBOU = null;
        XSSFWorkbook exelJtableExporter = null;
        JFileChooser exelfileChooser = new JFileChooser("D:\\duan1\\DuAn1_Khanh\\Exel");
        exelfileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXEL FILES", "xls", "xlsx", "xlsm");
        exelfileChooser.setFileFilter(fnef);
        int exelChooser = exelfileChooser.showSaveDialog(null);

        if (exelChooser == JFileChooser.APPROVE_OPTION) {

            try {
                exelJtableExporter = new XSSFWorkbook();
                XSSFSheet exelSheet = exelJtableExporter.createSheet("JTable Sheet");
                for (int i = 0; i < model.getRowCount(); i++) {
                    XSSFRow exelRow = exelSheet.createRow(i);

                    for (int j = 0; j < model.getColumnCount(); j++) {
                        XSSFCell exelCell = exelRow.createCell(j);
                        exelCell.setCellValue(model.getValueAt(i, j).toString());
                    }

                }
                exelFOU = new FileOutputStream(exelfileChooser.getSelectedFile() + ".xls");
                exelBOU = new BufferedOutputStream(exelFOU);
                exelJtableExporter.write(exelBOU);
                JOptionPane.showMessageDialog(this, "Export Successfully !");
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if(exelBOU != null){
                        exelBOU.close();
                    }
                    if(exelFOU != null){
                        exelFOU.close();
                    }
                    if(exelJtableExporter != null){

                    }
                } catch (IOException ex) {

                    java.util.logging.Logger.getLogger(SinhVienJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnExel5ActionPerformed

    void init() {
        fillcomboboxChuyenNganh();
        fillComboBoxHocKi();
        txt_MaNV.setText(nvdao.selectByMaTK(Auth.user.getMaTK()).getMaNhanVien());
        txtNgayTao.setText(ChuyenDoi.DinhDangNgay(ChuyenDoi.now()));

    }
int i = 1;
    void FillTableHoaDon() {
        if (cbbKH.getSelectedItem().toString() != null) {
            try {
                DefaultTableModel model = (DefaultTableModel) tbl_HoaDon.getModel();
                model.setRowCount(0);
                String MaSV = cbbKH.getSelectedItem().toString();
                List<HoaDon> list = hddao.selectByMaSV(MaSV);
                for (HoaDon hd : list) {
                    int slmh = 0;
                    float money = 0;
                    List<MonHoc> mh = mhDao.selectByHocKyandmoney(hd.getHocKy(), hd.getMaChuyenNganh());
                    for (MonHoc monHoc : mh) {
                        slmh++;
                        money += monHoc.getHocPhi();
                    }
                    Object[] row = {
                      hd.getMaHoaDon(),
                        hd.getMaSinhVien(),
                     hd.getMaChuyenNganh(),
                          hd.getHocKy(),
                             Math.round(money),
                                   slmh,
//                     XDate.toString(hd.getNgayTaoHoaDon(), "dd-MM-yyyy"),
                        hd.isTinhTrang() == true ? "Đã Thanh Toán" : "Chưa Thanh Toán"
                    };
                    model.addRow(row);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            DefaultTableModel model = (DefaultTableModel) tbl_HoaDon.getModel();
            model.setRowCount(0);
        }
    }

    void Filltable(String MaHK) {
        DefaultTableModel model = (DefaultTableModel) tblMonHoc.getModel();
        model.setRowCount(0);
        try {
            List<MonHoc> list = mhDao.selectByHocKy(MaHK);
            for (MonHoc mh : list) {
                Object[] row = {
                    mh.getMaMonHoc(),
                    mh.getTenMonHoc(),
                    mh.getHocPhi(),
                    mh.getHocKy()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillcomboboxChuyenNganh() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbb_ChuyenNganh.getModel();
        model.removeAllElements();
        try {
            List<ChuyenNganh> list = cnDao.selectAll();
            for (ChuyenNganh cn : list) {
                model.addElement(cn.getMaChuyenNganh());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillcomboboxLopHoc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbb_Lophoc.getModel();
        model.removeAllElements();
        if (cbb_ChuyenNganh.getSelectedItem().toString() != null) {
            String MaCN = cbb_ChuyenNganh.getSelectedItem().toString();
            try {
                List<LopHoc> list = lhDao.selectByChuyenNganh(MaCN);
                for (LopHoc lh : list) {
                    model.addElement(lh.getMaLopHoc());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    void fillComboBoxSinhVien() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbKH.getModel();
        model.removeAllElements();
        if (cbb_Lophoc.getSelectedItem().toString() != null) {
            try {
                String MaLH = cbb_Lophoc.getSelectedItem().toString();
                List<SinhVien> list = svDao.selectSVByMaLH(MaLH);
                for (SinhVien sv : list) {
                    model.addElement(sv.getMaSinhVien());
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Lỗi Truy Vấn");
            }
        }
    }

  void fillComboBoxHocKi() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbb_Hocky.getModel();
        model.removeAllElements();
        System.out.println(cbbKH.getSelectedItem());
        if(cbbKH.getSelectedItem() != null ){
            String MaSV = cbbKH.getSelectedItem().toString();
            try {
                List<HocKy> list = hkdao.selectAllNotIN(MaSV);
                for (HocKy hk : list) {
                    model.addElement(hk.getMaHocKy());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    void DeletaRowTable() {
        DefaultTableModel tblModel = (DefaultTableModel) tbl_HoaDon.getModel();
        if (tbl_HoaDon.getSelectedRowCount() == 1) {
            tblModel.removeRow(tbl_HoaDon.getSelectedRow());
        } else {
            if (tbl_HoaDon.getSelectedRowCount() == 0) {
                MsgBox.alert(this, "Bạn Chưa Chọn Gì Cả");
            } else {
                MsgBox.alert(this, "Bạn Chỉ Được Phép Xóa Từng Dòng");
            }
        }
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scrollbar;
    private rojeru_san.complementos.RSButtonHover btnExel5;
    private rojeru_san.complementos.RSButtonHover btnPrint;
    private rojeru_san.complementos.RSButtonHover btnThanhToan;
    private rojeru_san.complementos.RSButtonHover btn_Them;
    private rojeru_san.complementos.RSButtonHover btn_Xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbKH;
    private javax.swing.JComboBox<String> cbb_ChuyenNganh;
    private javax.swing.JComboBox<String> cbb_Hocky;
    private javax.swing.JComboBox<String> cbb_Lophoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdochuatt;
    private javax.swing.JRadioButton rdott;
    private rojeru_san.complementos.RSTableMetro tblMonHoc;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txt_MaNV;
    // End of variables declaration//GEN-END:variables
}
