/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.duan1.X.DBConnection;
import com.mycompany.duan1.X.DatabaseConnection;
import com.mycompany.duan1.X.MsgBox;
import com.mycompany.duan1.X.XJdbc;
import com.mycompany.duan1.controller.MyCombobox;
import com.mycompany.duan1.dao.ChuyenNganhDao;
import com.mycompany.duan1.dao.DAOHoaDon;
import com.mycompany.duan1.dao.HoaDonDao;
import com.mycompany.duan1.dao.HocKyDao;
import com.mycompany.duan1.dao.MonHocDao;
import com.mycompany.duan1.dao.NhanVienDao;
import com.mycompany.duan1.dao.SinhVienDao;
import com.mycompany.duan1.model.ChuyenDoi;
import com.mycompany.duan1.model.ChuyenNganh;
import com.mycompany.duan1.model.HoaDon;
import com.mycompany.duan1.model.HocKy;
import com.mycompany.duan1.model.MonHoc;
import com.mycompany.duan1.model.NhanVien;
import com.mycompany.duan1.model.SinhVien;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.util.logging.Level;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import org.apache.log4j.Logger;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
import scrollbar.ScrollBarCustom;
/**
 *
 * @author ADMIN
 */
public class ThanhToanDichVu extends javax.swing.JPanel {

    /**
     * Creates new form ThanhToanDichVu
     */
    public ThanhToanDichVu() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSoHoaDon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        cbbKH = new javax.swing.JComboBox<>();
        txtmachuyennganh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCTHD1 = new javax.swing.JTable();
        txtTongTien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtmamonhoc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rdott = new javax.swing.JRadioButton();
        rdochuatt = new javax.swing.JRadioButton();
        Scrollbar = new javax.swing.JScrollPane();
        tblMonHoc = new rojeru_san.complementos.RSTableMetro();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        btnThanhToan = new rojeru_san.complementos.RSButtonHover();
        cbbmahocky = new combobox.MaHocKy();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Ngày tạo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 14, -1, -1));
        jPanel1.add(txtNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 140, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Số hóa đơn");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));
        jPanel1.add(txtSoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 143, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Nhân viên");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 143, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Địa chỉ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Sinh Viên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 190, -1));

        cbbKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKHItemStateChanged(evt);
            }
        });
        cbbKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKHActionPerformed(evt);
            }
        });
        jPanel1.add(cbbKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 190, -1));

        txtmachuyennganh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmachuyennganhKeyReleased(evt);
            }
        });
        jPanel1.add(txtmachuyennganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 190, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Mã Chuyên Ngành");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("Tình Trạng");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Điện thoại");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        txtDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienThoaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 130, -1));

        tblCTHD1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Chuyên Ngành", "Thành tiền", "Học Kỳ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCTHD1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 780, 280));

        txtTongTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTongTienFocusLost(evt);
            }
        });
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });
        jPanel1.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 172, 28));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 51));
        jLabel10.setText("Tổng cộng");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, -1, -1));
        jPanel1.add(txtmamonhoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 130, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("Mã MH");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, -1, -1));

        buttonGroup1.add(rdott);
        rdott.setSelected(true);
        rdott.setText("Đã T/T");
        jPanel1.add(rdott, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, -1, -1));

        buttonGroup1.add(rdochuatt);
        rdochuatt.setText("Chưa T/T");
        jPanel1.add(rdochuatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, -1, -1));

        tblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Môn Học", "Mã Chuyên Ngành", "Học Phí", "Học Kỳ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonHoc.setCellSelectionEnabled(true);
        tblMonHoc.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblMonHoc.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblMonHoc.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblMonHoc.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblMonHoc.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        tblMonHoc.setColorSelForeground(new java.awt.Color(204, 204, 204));
        tblMonHoc.setRowHeight(25);
        tblMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonHocMouseClicked(evt);
            }
        });
        Scrollbar.setViewportView(tblMonHoc);

        jPanel1.add(Scrollbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 291, 160));

        rSButtonHover1.setBackground(new java.awt.Color(204, 0, 51));
        rSButtonHover1.setText("XÓA");
        rSButtonHover1.setColorHover(new java.awt.Color(255, 51, 51));
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 130, -1));

        btnThanhToan.setBackground(new java.awt.Color(204, 0, 51));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.setColorHover(new java.awt.Color(255, 51, 51));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        jPanel1.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, 130, -1));

        cbbmahocky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmahockyActionPerformed(evt);
            }
        });
        jPanel1.add(cbbmahocky, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public static String MaMonHoc;
public static String MaChuyenNganh;
public static String HocKy;
public static boolean TinhTrang; 
public static String MaSinhVien;
    private double TinhTien() {
        double tongTien = 0;
        for (int i = 0; i < tblCTHD1.getRowCount(); i++) {
            tongTien += ChuyenDoi.ChuyenTien(tblCTHD1.getValueAt(i, 2).toString());
        }

        return tongTien;
    }
    private void cbbKHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKHItemStateChanged

     
    }//GEN-LAST:event_cbbKHItemStateChanged

    private void cbbKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKHActionPerformed
chonChuyenDe();     // TODO add your handling code here:
    }//GEN-LAST:event_cbbKHActionPerformed

    private void txtmachuyennganhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmachuyennganhKeyReleased

    }//GEN-LAST:event_txtmachuyennganhKeyReleased
    HoaDonDao hddao = new HoaDonDao();
    private void txtDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienThoaiActionPerformed

    private void tblMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonHocMouseClicked
     if (evt.getClickCount() >= 1) {
            MaMonHoc = tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(), 0).toString();
            MaChuyenNganh = tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(), 1).toString();
            double thanhTien, hocphi;
            hocphi = Double.parseDouble(tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(), 2).toString());
            thanhTien = hocphi ;
            HocKy = tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(), 3).toString();
           

       ;

            ThemSanPhamTbCTHD(MaChuyenNganh, hocphi, thanhTien, HocKy);
            txtTongTien.setText(ChuyenDoi.DinhDangTien(TinhTien()));
            txtmachuyennganh.setText(tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(),1).toString());
            txtmamonhoc.setText(tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(),0).toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblMonHocMouseClicked

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtTongTienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTongTienFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienFocusLost

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
DeletaRowTable();
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        if (tblMonHoc.getRowCount() <= 0) {
            MsgBox.alert(this,"Chưa chọn sản phẩm!");
            return;
        }
   
        
        HoaDon hd = getForm();
                //Thêm hóa đơn vào database
                hddao.insert(hd);
                MsgBox.alert(this, "Đã Thanh Toán Cho Sinh Viên");

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void cbbmahockyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmahockyActionPerformed
filltablemonhoc();        // TODO add your handling code here:
    }//GEN-LAST:event_cbbmahockyActionPerformed
     private void ThemSanPhamTbCTHD( String MaChuyenNganh, double HocPhi,
           double ThanhTien, String HocKy) {

        DefaultTableModel tbModel = (DefaultTableModel)tblCTHD1.getModel();

        Object obj[] = new Object[8];

        obj[0] = tbModel.getRowCount() + 1;
        obj[1] = MaChuyenNganh;
        obj[2] = ChuyenDoi.ChuyenTien(String.valueOf(HocPhi));
        obj[3] = HocKy;
     
        tbModel.addRow(obj);
    }
  void fixTable() {
        Scrollbar.getViewport().setBackground(Color.WHITE);
        Scrollbar.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        Scrollbar.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        Scrollbar.setBorder(new EmptyBorder(5, 10, 5, 10));
    }
    void init(){
      Filltable();
      fillComboBoxNhanVien();
      fillComboBoxsINHVien();
      txtNgayTao.setText(ChuyenDoi.DinhDangNgay(ChuyenDoi.now()));
 fillComboBoxHocKy();
    
  }
    SinhVienDao svdao = new SinhVienDao();
    MonHocDao mhDao = new MonHocDao();
    NhanVienDao nvdao = new NhanVienDao();
void Filltable(){
    DefaultTableModel model = (DefaultTableModel)tblMonHoc.getModel();
    model.setRowCount(0);
    List<MonHoc> list =  mhDao.selectAll();
    for (MonHoc mh : list) {
     Object [] row =  {mh.getMaMonHoc(),mh.getMaChuyenNganh(),mh.getHocPhi(),mh.getHocKy()};
        model.addRow(row);
        
    }
}
    void fillComboBoxNhanVien(){
        try {
               DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox2.getModel();
        model.removeAllElements();
        List<NhanVien> list = nvdao.selectAll();
        for(NhanVien cd: list){
            model.addElement(cd);
        }
//        this.fillComboBoxLopHoc();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn");
        }
     
    }
       void fillComboBoxsINHVien(){
        try {
               DefaultComboBoxModel model = (DefaultComboBoxModel) cbbKH.getModel();
        model.removeAllElements();
        List<SinhVien> list = svdao.selectAll();
        for(SinhVien cd: list){
            model.addElement(cd);
        }
//        this.fillComboBoxLopHoc();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Truy Vấn");
        }
     
    }
        void chonChuyenDe(){
        SinhVien sinhVien = (SinhVien) cbbKH.getSelectedItem();
        txtDiaChi.setText(String.valueOf(sinhVien.getDiaChi()));
        txtDienThoai.setText(String.valueOf(sinhVien.getSDT()));
 }
     HoaDon getForm(){
           HoaDon hd = new HoaDon();
        hd.setSoHoaDon(txtSoHoaDon.getText());
        hd.setNgayTaoHoaDon(ChuyenDoi.LayNgay(txtNgayTao.getText()));
        hd.setMaNhanVien(String.valueOf(jComboBox2.getSelectedItem())); //Đang gán cố định,
        hd.setMaSinhVien(String.valueOf(cbbKH.getSelectedItem()));
        hd.setHocPhi(ChuyenDoi.ChuyenTien(txtTongTien.getText()));
        hd.setMaChuyenNganhSV(txtmachuyennganh.getText());
        hd.setMaMonHoc(txtmamonhoc.getText());
        hd.setTongTien(ChuyenDoi.ChuyenTien(txtTongTien.getText()));
        hd.setTinhTrang(rdott.isSelected());
        hd.setTinhTrang(rdochuatt.isSelected());
        hd.setHocKy(tblMonHoc.getValueAt(tblMonHoc.getSelectedRow(),3).toString());
        return hd;
        
    }
    void DeletaRowTable(){
        DefaultTableModel tblModel = (DefaultTableModel)tblCTHD1.getModel();
        if(tblCTHD1.getSelectedRowCount() == 1){
            tblModel.removeRow(tblCTHD1.getSelectedRow());
        }else{
            if(tblCTHD1.getSelectedRowCount() == 0){
                MsgBox.alert(this, "Bạn Chưa Chọn Gì Cả");
            }else{
                  MsgBox.alert(this, "Bạn Chỉ Được Phép Xóa Từng Dòng");
            }
        }
    }
    HocKyDao hkdao = new HocKyDao();
    void fillComboBoxHocKy() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbmahocky.getModel();
        model.removeAllElements();
        try {
            List<HocKy> list = hkdao.selectAll();
            for (HocKy cd : list) {
                model.addElement(cd.getMaHocKy());
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi Truy Vấn");
        }

    }
    MonHocDao mhdao = new MonHocDao();
      void filltablemonhoc() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblMonHoc.getModel();
          
              model.setRowCount(0);
            try {
                String hocky = cbbmahocky.getSelectedItem().toString();
                List<MonHoc> list = mhdao.selectByHocKy(hocky);
                
                for (MonHoc cd : list) {
                      Object [] row =  {cd.getMaMonHoc(),cd.getMaChuyenNganh(),cd.getHocPhi(),cd.getHocKy()};
        model.addRow(row);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi Truy Vấn");
        }

    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scrollbar;
    private rojeru_san.complementos.RSButtonHover btnThanhToan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbKH;
    private combobox.MaHocKy cbbmahocky;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private javax.swing.JRadioButton rdochuatt;
    private javax.swing.JRadioButton rdott;
    private javax.swing.JTable tblCTHD1;
    private rojeru_san.complementos.RSTableMetro tblMonHoc;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtSoHoaDon;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtmachuyennganh;
    private javax.swing.JTextField txtmamonhoc;
    // End of variables declaration//GEN-END:variables
}
